# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-UU47zJepjOUBMnhQNWvQH0HupMWo105
"""

symptom_department_map = {
    'chest pain': 'Cardiology',
    'headache': 'Neurology',
    'skin rash': 'Dermatology',
    'stomach ache': 'Gastroenterology',
    'eye pain': 'Ophthalmology',
    'fever': 'General Medicine',
    'cough': 'Pulmonology'
}

user_input = input("Describe your symptom: ").lower()

matched = False
for symptom, department in symptom_department_map.items():
    if symptom in user_input:
        print(f"You should consult the {department} department.")
        matched = True
        break

if not matched:
    print("Symptom not recognized. Please consult General Medicine.")